title: QuanTOR
description: >
    
    Quantitative Analysis of Textual Organisation across Registers.
    A WEAVE project funded by the German Research Council and the Swiss National Fund (project no. 528467412).

logo: quantor_logo.png

show_downloads: false

theme: jekyll-theme-minimal
