title: QuanTOR
description: >
    A WEAVE project funded by the German Research Council and the Swiss National Fund (project no. 528467412).

logo: quantor_logo.png

header_pages: message

theme: jekyll-theme-minimal
show_downloads: false

